export enum UserType {
  SUPER_USER = 'SUPER_USER',
  APP_ORGANIZATION = 'APP_ORGANIZATION',
  APP_MANAGER = 'APP_MANAGER',
  APP_WORKER = 'APP_WORKER',
  ORGANIZATION = 'ORGANIZATION',
  MANAGER = 'MANAGER',
  WORKER = 'WORKER',
  MEMBER = 'MEMBER',
  PARTNER = 'PARTNER',
  DOCTOR = 'DOCTOR',
  REFERRAL = 'REFERRAL',
  EXPERT = 'EXPERT',
}
