image: node:19.0.1

pipelines:
  branches:
    dev-deploy:
      - step:
          name: Build and Push to dev Container Registry
          services:
            - docker
          script:
            - docker login registry.digitalocean.com -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker build -t registry.digitalocean.com/$DOCKER_REGISTRY_NAME/senlife-container:latest .
            - docker push registry.digitalocean.com/$DOCKER_REGISTRY_NAME/senlife-container:latest
    production-deploy:
      - step:
          name: Build and Push to production Container Registry
          services:
            - docker
          script:
            - docker login registry.digitalocean.com -u $DOCKER_USER -p $DOCKER_PASSWORD
            - docker build -t registry.digitalocean.com/$DOCKER_REGISTRY_NAME/senlife-production-container:latest .
            - docker push registry.digitalocean.com/$DOCKER_REGISTRY_NAME/senlife-production-container:latest
