import { UserPermissionsType } from '../../user/enums/user-permission.enum';

export class Permission {
  static SUPER_USER_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_APP_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_APP_MANAGER,
    UserPermissionsType.CAN_CREATE_APP_WORKER,
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,

    UserPermissionsType.CAN_ADD_USE_CASE,
    UserPermissionsType.CAN_EDIT_USE_CASE,
    UserPermissionsType.CAN_DELETE_USE_CASE,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_ADD_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_EDIT_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_DELETE_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_VIEW_SANDBOX_INSIGHT_CATEGORY,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_ADD_EXPERT_PROFILE,
    UserPermissionsType.CAN_VIEW_EXPERT_PROFILE,
    UserPermissionsType.CAN_EDIT_EXPERT_PROFILE,
    UserPermissionsType.CAN_DELETE_EXPERT_PROFILE,

    UserPermissionsType.CAN_ADD_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_EDIT_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_DELETE_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,

    UserPermissionsType.CAN_VIEW_SUGGESTIONS,

    UserPermissionsType.CAN_ADD_CATEGORY,
    UserPermissionsType.CAN_VIEW_CATEGORY,
    UserPermissionsType.CAN_EDIT_CATEGORY,
    UserPermissionsType.CAN_DELETE_CATEGORY,

    UserPermissionsType.CAN_ADD_PREGNANCY_INFO,

    UserPermissionsType.CAN_VIEW_PREGNANCY_INFO,
    UserPermissionsType.CAN_EDIT_PREGNANCY_INFO,
    UserPermissionsType.CAN_DELETE_PREGNANCY_INFO,

    UserPermissionsType.CAN_ADD_ENTRY_CATEGORY,
    UserPermissionsType.CAN_VIEW_ENTRY_CATEGORY,
    UserPermissionsType.CAN_EDIT_ENTRY_CATEGORY,
    UserPermissionsType.CAN_DELETE_ENTRY_CATEGORY,

    UserPermissionsType.CAN_ADD_ENTRY,
    UserPermissionsType.CAN_VIEW_ENTRY,
    UserPermissionsType.CAN_EDIT_ENTRY,
    UserPermissionsType.CAN_DELETE_ENTRY,

    UserPermissionsType.CAN_ADD_CHALLENGE,
    UserPermissionsType.CAN_VIEW_CHALLENGE,
    UserPermissionsType.CAN_EDIT_CHALLENGE,
    UserPermissionsType.CAN_DELETE_CHALLENGE,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
  static APP_ORGANIZATION_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_APP_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_APP_MANAGER,
    UserPermissionsType.CAN_CREATE_APP_WORKER,
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,

    UserPermissionsType.CAN_ADD_USE_CASE,
    UserPermissionsType.CAN_EDIT_USE_CASE,
    UserPermissionsType.CAN_DELETE_USE_CASE,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_ADD_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_EDIT_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_DELETE_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_VIEW_SANDBOX_INSIGHT_CATEGORY,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_ADD_EXPERT_PROFILE,
    UserPermissionsType.CAN_VIEW_EXPERT_PROFILE,
    UserPermissionsType.CAN_EDIT_EXPERT_PROFILE,
    UserPermissionsType.CAN_DELETE_EXPERT_PROFILE,

    UserPermissionsType.CAN_ADD_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_EDIT_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_DELETE_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,

    UserPermissionsType.CAN_VIEW_SUGGESTIONS,

    UserPermissionsType.CAN_ADD_CATEGORY,
    UserPermissionsType.CAN_VIEW_CATEGORY,
    UserPermissionsType.CAN_EDIT_CATEGORY,
    UserPermissionsType.CAN_DELETE_CATEGORY,

    UserPermissionsType.CAN_ADD_PREGNANCY_INFO,

    UserPermissionsType.CAN_VIEW_PREGNANCY_INFO,
    UserPermissionsType.CAN_EDIT_PREGNANCY_INFO,
    UserPermissionsType.CAN_DELETE_PREGNANCY_INFO,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
  static APP_MANAGER_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_APP_MANAGER,
    UserPermissionsType.CAN_CREATE_APP_WORKER,
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,

    UserPermissionsType.CAN_ADD_USE_CASE,
    UserPermissionsType.CAN_EDIT_USE_CASE,
    UserPermissionsType.CAN_DELETE_USE_CASE,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_ADD_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_EDIT_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_DELETE_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_VIEW_SANDBOX_INSIGHT_CATEGORY,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_ADD_EXPERT_PROFILE,
    UserPermissionsType.CAN_VIEW_EXPERT_PROFILE,
    UserPermissionsType.CAN_EDIT_EXPERT_PROFILE,
    UserPermissionsType.CAN_DELETE_EXPERT_PROFILE,

    UserPermissionsType.CAN_ADD_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_EDIT_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_DELETE_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,

    UserPermissionsType.CAN_VIEW_SUGGESTIONS,

    UserPermissionsType.CAN_ADD_CATEGORY,
    UserPermissionsType.CAN_VIEW_CATEGORY,
    UserPermissionsType.CAN_EDIT_CATEGORY,
    UserPermissionsType.CAN_DELETE_CATEGORY,

    UserPermissionsType.CAN_ADD_PREGNANCY_INFO,

    UserPermissionsType.CAN_VIEW_PREGNANCY_INFO,
    UserPermissionsType.CAN_EDIT_PREGNANCY_INFO,
    UserPermissionsType.CAN_DELETE_PREGNANCY_INFO,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
  static APP_WORKER_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,

    UserPermissionsType.CAN_ADD_USE_CASE,
    UserPermissionsType.CAN_EDIT_USE_CASE,
    UserPermissionsType.CAN_DELETE_USE_CASE,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_ADD_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_EDIT_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_DELETE_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_VIEW_SANDBOX_INSIGHT_CATEGORY,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_ADD_EXPERT_PROFILE,
    UserPermissionsType.CAN_VIEW_EXPERT_PROFILE,
    UserPermissionsType.CAN_EDIT_EXPERT_PROFILE,
    UserPermissionsType.CAN_DELETE_EXPERT_PROFILE,

    UserPermissionsType.CAN_ADD_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_EDIT_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_DELETE_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,

    UserPermissionsType.CAN_VIEW_SUGGESTIONS,

    UserPermissionsType.CAN_ADD_CATEGORY,
    UserPermissionsType.CAN_VIEW_CATEGORY,
    UserPermissionsType.CAN_EDIT_CATEGORY,
    UserPermissionsType.CAN_DELETE_CATEGORY,

    UserPermissionsType.CAN_ADD_PREGNANCY_INFO,

    UserPermissionsType.CAN_VIEW_PREGNANCY_INFO,
    UserPermissionsType.CAN_EDIT_PREGNANCY_INFO,
    UserPermissionsType.CAN_DELETE_PREGNANCY_INFO,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
  static ORGANIZATION_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,
    // AI feature
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];

  static MANAGER_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_APP_MANAGER,
    UserPermissionsType.CAN_CREATE_APP_WORKER,
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,

    UserPermissionsType.CAN_ADD_USE_CASE,
    UserPermissionsType.CAN_EDIT_USE_CASE,
    UserPermissionsType.CAN_DELETE_USE_CASE,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_ADD_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_EDIT_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_DELETE_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_VIEW_SANDBOX_INSIGHT_CATEGORY,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_ADD_EXPERT_PROFILE,
    UserPermissionsType.CAN_VIEW_EXPERT_PROFILE,
    UserPermissionsType.CAN_EDIT_EXPERT_PROFILE,
    UserPermissionsType.CAN_DELETE_EXPERT_PROFILE,

    UserPermissionsType.CAN_ADD_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_EDIT_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_DELETE_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,

    UserPermissionsType.CAN_VIEW_SUGGESTIONS,

    UserPermissionsType.CAN_ADD_CATEGORY,
    UserPermissionsType.CAN_VIEW_CATEGORY,
    UserPermissionsType.CAN_EDIT_CATEGORY,
    UserPermissionsType.CAN_DELETE_CATEGORY,

    UserPermissionsType.CAN_ADD_PREGNANCY_INFO,

    UserPermissionsType.CAN_VIEW_PREGNANCY_INFO,
    UserPermissionsType.CAN_EDIT_PREGNANCY_INFO,
    UserPermissionsType.CAN_DELETE_PREGNANCY_INFO,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
  static WORKER_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_ADD_POSTS,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_EDIT_POSTS,
    UserPermissionsType.CAN_DELETE_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_ADD_TUTORIALS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_EDIT_TUTORIALS,
    UserPermissionsType.CAN_DELETE_TUTORIALS,
    UserPermissionsType.CAN_ADD_FAQ,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_EDIT_FAQ,
    UserPermissionsType.CAN_DELETE_FAQ,
    UserPermissionsType.CAN_ADD_TAG,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_EDIT_TAG,
    UserPermissionsType.CAN_DELETE_TAG,
    UserPermissionsType.CAN_ADD_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_VIEW_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_EDIT_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_DELETE_BUSINESS_ACCOUNT,
    UserPermissionsType.CAN_ADD_PROMO_CODE,
    UserPermissionsType.CAN_VIEW_PROMO_CODE,
    UserPermissionsType.CAN_EDIT_PROMO_CODE,
    UserPermissionsType.CAN_DELETE_PROMO_CODE,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_MEDICATIONS,
    UserPermissionsType.CAN_EXPORT_ALLERGIES,
    UserPermissionsType.CAN_EXPORT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EXPORT_DAILY_NOTES,
    UserPermissionsType.CAN_EXPORT_DAILY_TRACKING,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_CREATE_ACCOUNT,
    UserPermissionsType.CAN_LOGIN_USER,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,
    // Allowed Creating of User Types
    UserPermissionsType.CAN_CREATE_ORGANIZATION,
    UserPermissionsType.CAN_CREATE_MANAGER,
    UserPermissionsType.CAN_CREATE_WORKER,
    UserPermissionsType.CAN_CREATE_MEMBER,
    UserPermissionsType.CAN_CREATE_POST,
    UserPermissionsType.CAN_CREATE_DOCTOR,
    UserPermissionsType.CAN_OTHER_VIEW_MY_DESCENDANTS,

    UserPermissionsType.CAN_ADD_USE_CASE,
    UserPermissionsType.CAN_EDIT_USE_CASE,
    UserPermissionsType.CAN_DELETE_USE_CASE,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_ADD_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_EDIT_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_DELETE_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_VIEW_SANDBOX_INSIGHT_CATEGORY,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_ADD_EXPERT_PROFILE,
    UserPermissionsType.CAN_VIEW_EXPERT_PROFILE,
    UserPermissionsType.CAN_EDIT_EXPERT_PROFILE,
    UserPermissionsType.CAN_DELETE_EXPERT_PROFILE,

    UserPermissionsType.CAN_ADD_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_EDIT_CATEGORY_SYMPTOM,
    UserPermissionsType.CAN_DELETE_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,

    UserPermissionsType.CAN_VIEW_SUGGESTIONS,

    UserPermissionsType.CAN_ADD_CATEGORY,
    UserPermissionsType.CAN_VIEW_CATEGORY,
    UserPermissionsType.CAN_EDIT_CATEGORY,
    UserPermissionsType.CAN_DELETE_CATEGORY,

    UserPermissionsType.CAN_ADD_PREGNANCY_INFO,

    UserPermissionsType.CAN_VIEW_PREGNANCY_INFO,
    UserPermissionsType.CAN_EDIT_PREGNANCY_INFO,
    UserPermissionsType.CAN_DELETE_PREGNANCY_INFO,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
  static MEMBER_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_ADD_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_EDIT_MEDICATIONS,
    UserPermissionsType.CAN_DELETE_MEDICATIONS,
    UserPermissionsType.CAN_ADD_ALLERGIES,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_EDIT_ALLERGIES,
    UserPermissionsType.CAN_DELETE_ALLERGIES,
    UserPermissionsType.CAN_ADD_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_EDIT_CONTACT_KEYS,
    UserPermissionsType.CAN_DELETE_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_ADD_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_EDIT_BEHAVIOUR_TRAIT,
    UserPermissionsType.CAN_DELETE_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_ADD_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EDIT_DIVERSE_CONDITION,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_DELETE_DIVERSE_CONDITION,
    UserPermissionsType.CAN_EXPORT_CHILD_DATA,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_ENTRY_CATEGORY,
    UserPermissionsType.CAN_EDIT_ENTRY_CATEGORY,
    UserPermissionsType.CAN_ADD_ENTRY_CATEGORY,
    UserPermissionsType.CAN_DELETE_ENTRY_CATEGORY,

    // AI feature
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_SHARE_IMPORTANT_FILES,

    UserPermissionsType.CAN_VIEW_CATEGORY_SYMPTOM,

    UserPermissionsType.CAN_ADD_SYMPTOM,
    UserPermissionsType.CAN_VIEW_SYMPTOM,
    UserPermissionsType.CAN_EDIT_SYMPTOM,
    UserPermissionsType.CAN_DELETE_SYMPTOM,
    UserPermissionsType.CAN_ADD_ENTRY,
    UserPermissionsType.CAN_VIEW_ENTRY,
    UserPermissionsType.CAN_EDIT_ENTRY,
    UserPermissionsType.CAN_DELETE_ENTRY,
    UserPermissionsType.CAN_ADD_CHALLENGE,
    UserPermissionsType.CAN_VIEW_CHALLENGE,
    UserPermissionsType.CAN_EDIT_CHALLENGE,
    UserPermissionsType.CAN_DELETE_CHALLENGE,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];

  static POST_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,

    // AI feature
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];

  static DOCTOR_DEFAULT_PERMISSIONS: Array<UserPermissionsType> = [
    UserPermissionsType.CAN_VIEW_MEDICATIONS,
    UserPermissionsType.CAN_VIEW_ALLERGIES,
    UserPermissionsType.CAN_VIEW_CONTACT_KEYS,
    UserPermissionsType.CAN_CALL_CONTACT_KEYS,
    UserPermissionsType.CAN_VIEW_BEHAVIOUR_TRAIT,

    UserPermissionsType.CAN_ADD_DAILY_NOTES,
    UserPermissionsType.CAN_VIEW_DAILY_NOTES,
    UserPermissionsType.CAN_EDIT_DAILY_NOTES,
    UserPermissionsType.CAN_DELETE_DAILY_NOTES,
    UserPermissionsType.CAN_ADD_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_DAILY_TRACKING,
    UserPermissionsType.CAN_EDIT_DAILY_TRACKING,
    UserPermissionsType.CAN_DELETE_DAILY_TRACKING,
    UserPermissionsType.CAN_VIEW_POSTS,
    UserPermissionsType.CAN_SHARE_POSTS,
    UserPermissionsType.CAN_LIKE_DISLIKE_POSTS,
    UserPermissionsType.CAN_VIEW_TUTORIALS,
    UserPermissionsType.CAN_VIEW_FAQ,
    UserPermissionsType.CAN_VIEW_TAG,
    UserPermissionsType.CAN_VIEW_DIVERSE_CONDITION,
    UserPermissionsType.CAN_ADD_COMMENT,
    UserPermissionsType.CAN_EDIT_COMMENT,
    UserPermissionsType.CAN_DELETE_COMMENT,
    UserPermissionsType.CAN_VIEW_COMMENT,

    // AI feature
    UserPermissionsType.CAN_VIEW_USE_CASE_CATEGORY,
    UserPermissionsType.CAN_VIEW_USE_CASE,
    UserPermissionsType.CAN_VIEW_INSIGHT,
    UserPermissionsType.CAN_ADD_INSIGHT,

    UserPermissionsType.CAN_ADD_IMPORTANT_FILES,
    UserPermissionsType.CAN_VIEW_IMPORTANT_FILES,
    UserPermissionsType.CAN_EDIT_IMPORTANT_FILES,
    UserPermissionsType.CAN_DELETE_IMPORTANT_FILES,
    UserPermissionsType.CAN_ADD_TASK,
    UserPermissionsType.CAN_VIEW_TASK,
    UserPermissionsType.CAN_EDIT_TASK,
    UserPermissionsType.CAN_DELETE_TASK,
  ];
}
