export const ERR_USER_NOT_ACTIVATED = 'ERR_USER_NOT_ACTIVATED';
export const ERR_EMAIL_NOT_FOUND = 'ERR_EMAIL_NOT_FOUND';
export const ERR_EMAIL_ALREADY_EXIST = 'ERR_EMAIL_ALREADY_EXIST';
export const ERR_ACCOUNT_WITH_EMAIL_ALREADY_REGISTERED = 'ERR_ACCOUNT_WITH_EMAIL_ALREADY_REGISTERED';
export const ERR_NOT_FOUND_USER = 'ERR_NOT_FOUND_USER';
export const ERR_GOOGLE_API = 'ERR_GOOGLE_API';
export const ERR_APPLE_API = 'ERR_APPLE_API';

export const ERR_EMAIL_OR_PASSWORD_IS_INCORRECT = 'ERR_EMAIL_OR_PASSWORD_IS_INCORRECT';
export const ERR_NOT_FOUND_TAG = 'ERR_NOT_FOUND_TAG';
export const ERR_NOT_FOUND_AI_INSIGHTS = 'ERR_NOT_FOUND_AI_INSIGHTS';
export const ERR_NOT_FOUND_POST = 'ERR_NOT_FOUND_POST';
export const ERR_NOT_FOUND_ADMIN = 'ERR_NOT_FOUND_ADMIN';
export const ERR_EMAIL_OR_PASSWORD_INCORRECT = 'ERR_EMAIL_OR_PASSWORD_INCORRECT';
export const ERR_NOT_FOUND_COMMENT = 'ERR_NOT_FOUND_COMMENT';
export const ERR_GENERATE_TOKEN = 'ERR_GENERATE_TOKEN';
export const ERR_EXPIRED_CODE = 'ERR_EXPIRED_CODE';
export const ERR_NOT_FOUND_CHILD = 'ERR_NOT_FOUND_CHILD';
export const ERR_SEND_MAIL = 'ERR_SEND_MAIL';
export const ERR_NOT_FOUND_ALLERGIE = 'ERR_NOT_FOUND_ALLERGIE';
export const ERR_NOT_FOUND_SYMPTOMS = 'ERR_NOT_FOUND_SYMPTOMS';

export const ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN';
export const ERR_SERVER_ERROR = 'ERR_SERVER_ERROR';
export const ERR_UNSUPPORTED_FILE = 'ERR_UNSUPPORTED_FILE';
export const ERR_UPLOAD_FAILED = 'ERR_UPLOAD_FAILED';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const ERR_INVALID_ARGUMENT = 'messaging/invalid-argument';
export const ERR_TOPIC_QUOTA_EXCEEDED = 'messaging/message-rate-exceeded';
export const ERR_TOPIC_EXPIRED = 'ERR_TOPIC_EXPIRED';
export const ERR_TOKEN_NOT_REGISTERED = 'messaging/registration-token-not-registered';
export const ERR_GENERATE_FIREBASE_DYNAMIC_LINK = 'ERR_GENERATE_FIREBASE_DYNAMIC_LINK';
export const ERR_INCORRECT_CODE = 'ERR_INCORRECT_CODE';
export const ERR_CODE_ALREADY_USED = 'ERR_CODE_ALREADY_USED';
export const ERR_ONLY_ADMINS_HAVE_ACCESS_TO_THIS_PLACE = 'ERR_ONLY_ADMINS_HAVE_ACCESS_TO_THIS_PLACE';
export const ERR_NOT_FOUND_MEDICATION = 'ERR_NOT_FOUND_MEDICATION';
export const ERR_NOT_FOUND_CONTACT = 'ERR_NOT_FOUND_CONTACT';
export const ERR_NOT_FOUND_BEHAVIOUR = 'ERR_NOT_FOUND_BEHAVIOUR';
export const ERR_NOT_FOUND_BEHAVIOUR_TRAIT = 'ERR_NOT_FOUND_BEHAVIOUR_TRAIT';
export const ERR_NOT_FOUND_ATTACHMENTS = 'ERR_NOT_FOUND_ATTACHMENTS';
export const ERR_NOT_FOUND_ATTACHMENT = 'ERR_NOT_FOUND_ATTACHMENT';
export const ERR_NOT_FOUND_USE_CASE = 'ERR_NOT_FOUND_USE_CASE';
export const ERR_NOT_FOUND_SUBSCRIPTION = 'ERR_NOT_FOUND_SUBSCRIPTION';
export const ERR_NOT_FOUND_AGES = 'ERR_NOT_FOUND_AGES';
export const ERR_NOT_FOUND_SESSION_DURATION = 'ERR_NOT_FOUND_SESSION_DURATION';
export const ERR_NOT_FOUND_EXPERT_SPECIALITIES = 'ERR_NOT_FOUND_EXPERT_SPECIALITIES';
export const ERR_NOT_FOUND_SESSION_DURATIONS = 'ERR_NOT_FOUND_SESSION_DURATIONS';
export const ERR_NOT_FOUND_EXPERT_PROFILE = 'ERR_NOT_FOUND_EXPERT_PROFILE';
export const DUPLICATE_ENTRY = 'ER_DUP_ENTRY';
export const ERR_INGISHT_REQUIRE_TIMELINE_TO_EXECUTE = 'ERR_INGISHT_REQUIRE_TIMELINE_TO_EXECUTE';

export const ERR_INGISHT_REQUIRE_CHILD_DATA_TYPE_TO_EXECUTE = 'ERR_INGISHT_REQUIRE_CHILD_DATA_TYPE_TO_EXECUTE';
export const ERR_NOT_FOUND_CATEGORY = 'ERR_NOT_FOUND_CATEGORY';
export const ERR_CHOOSE_ONE_OF_DAILY_NOTES_CHOICES = 'ERR_CHOOSE_ONE_OF_DAILY_NOTES_CHOICES';
export const ERR_ATTACHMENT_ALREADY_EXIST = 'ERR_ATTACHMENT_ALREADY_EXIST';
export const ERR_NOT_FOUND_DAILY_NOTE = 'ERR_NOT_FOUND_DAILY_NOTE';
export const ERR_PRIMARY_ATTACHMENTS_NOT_FOUND = 'ERR_PRIMARY_ATTACHMENTS_NOT_FOUND';
export const ERR_GENERATE_LINK = 'ERR_API_NOT_AVAILABLE';
export const ERR_EXPIRED_TOKEN_OR_INVALID = 'ERR_EXPIRED_TOKEN_OR_INVALID';
export const ERR_TOKEN_NOT_FOUND = 'ERR_TOKEN_NOT_FOUND';
export const ERR_CHILD_NOT_FOUND = 'ERR_CHILD_NOT_FOUND';
export const ERR_UNAUTHORIZED_SHARE_CHILD = 'ERR_UNAUTHORIZED_SHARE_CHILD';
export const ERR_UNAUTHORIZED_SHARE_AI_INSIGHT = 'ERR_UNAUTHORIZED_SHARE_AI_INSIGHT';
export const ERR_UNAUTHORIZED_ACCEPT_SHARE_AS_MEMBER = 'ERR_UNAUTHORIZED_ACCEPT_SHARE_AS_MEMBER';
export const ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED';
export const ERR_PERMISSIONS_UNAUTHORIZED = 'ERR_PERMISSIONS_UNAUTHORIZED';
export const ERR_USER_ALREADY_EXIST = 'ERR_USER_ALREADY_EXIST';
export const ERR_TOKEN_ALREADY_USED = 'ERR_TOKEN_ALREADY_USED';
export const ERR_NOT_FOUND_TRACKING_CATEGORY = 'ERR_NOT_FOUND_TRACKING_CATEGORY';
export const ERR_NOT_FOUND_TRACKING_TYPE = 'ERR_NOT_FOUND_TRACKING_TYPE';
export const ERR_NOT_FOUND_DAILY_TRACKING = 'ERR_NOT_FOUND_DAILY_TRACKING';
export const ERR_NOT_FOUND_FAQ = 'ERR_NOT_FOUND_FAQ';
export const ERR_CHOOSE_ONE_OF_DAILY_TRACKING_CHOICES = 'ERR_CHOOSE_ONE_OF_DAILY_TRACKING_CHOICES';
export const ERR_NOT_FOUND_TUTORIAL = 'ERR_NOT_FOUND_TUTORIAL';
export const ERR_START_DATE_BIGGER_THAN_END_DATE = 'ERR_START_DATE_BIGGER_THAN_END_DATE';

export const ERR_PUBLISHED_DATE_BIGGER_THAN_UNPUBLISHED_DATE = 'ERR_PUBLISHED_DATE_BIGGER_THAN_UNPUBLISHED_DATE';
export const ERR_NOTIFICATION = 'ERR_NOTIFICATION';
export const ERR_TRANSCRIPT = 'ERR_TRANSCRIPT';
export const ERR_SUMMARY = 'ERR_SUMMARY';
export const ERR_NOT_FOUND_NEURO_DIVERSE_CONDITIONS = 'ERR_NOT_FOUND_NEURO_DIVERSE_CONDITIONS';

export const ERR_YOU_ALREADY_ACCEPTED_CHILD_SHARE = 'ERR_YOU_ALREADY_ACCEPTED_CHILD_SHARE';
export const ERR_EXPORT_EMPTY = 'ERR_EXPORT_EMPTY';
export const ERR_EMPTY_DATA = 'ERR_EMPTY_DATA';
export const ERR_EXPORT_DOCUMENT = 'ERR_EXPORT_DOCUMENT';
export const ERR_NOT_FOUND_INVITATION = 'ERR_NOT_FOUND_INVITATION';
export const ERR_ONLY_EXPIRED_AND_PENDING_INVITATION_CAN_DELETE = 'ERR_ONLY_EXPIRED_AND_PENDING_INVITATION_CAN_DELETE';
export const ERR_NOT_FOUND_IN_THIS_COMMENT_POST_TYPE = 'ERR_NOT_FOUND_IN_THIS_COMMENT_POST_TYPE';

export const ERR_NO_SIBLING_FOR_ROOT_MEMBER_ORGANIZATION = 'ERR_NO_SIBLING_FOR_ROOT_MEMBER_ORGANIZATION';

export const ERR_THIS_USER_TYPE_FILTER_REQUIRE_NODE_ID = 'ERR_THIS_USER_TYPE_FILTER_REQUIRE_NODE_ID';

export const ERR_CREATE_EXPERT_PROFILE = 'ERR_CREATE_EXPERT_PROFILE';
export const ERR_NOT_FOUND_AUDIENCE = 'ERR_NOT_FOUND_AUDIENCE';
export const ERR_MAILCHIMP = 'ERR_MAILCHIMP';

export const ERR_MAX_UPLOAD_SIZE = 'ERR_MAX_UPLOAD_SIZE';
export const ERR_PRIMARY_ATTACHMENT_NOT_IN_ATTACHMENTS = 'ERR_PRIMARY_ATTACHMENT_NOT_IN_ATTACHMENTS';
export const ERR_CHILD_SHARE_CODE_NOT_FOUND = 'ERR_CHILD_SHARE_CODE_NOT_FOUND';
export const ERR_POST_TRANSLATION_ALREADY_EXIST = 'ERR_POST_TRANSLATION_ALREADY_EXIST';

export const ERR_FCM_TOKEN_EXIST = 'ERR_FCM_TOKEN_EXIST';
export const ERR_ESTIMATED_LMP_AT_REQUIRED = 'ERR_ESTIMATED_LMP_AT_REQUIRED';
export const ERR_ESTIMATED_CONCEPTION_AT_REQUIRED = 'ERR_ESTIMATED_CONCEPTION_AT_REQUIRED';
export const ERR_ESTIMATE_DELIVERY_AT_REQUIRED = 'ERR_ESTIMATE_DELIVERY_AT_REQUIRED';
export const ERR_WEEKS_OR_DAYS_REQUIRED = 'ERR_WEEKS_OR_DAYS_REQUIRED';
export const ERR_ESTIMATED_LMP_AT_GRATER_THAN_CURRENT_DATE = 'ERR_ESTIMATED_LMP_AT_GRATER_THAN_CURRENT_DATE';
export const ERR_NOT_FOUND_PREGNANCY_INFO = 'ERR_NOT_FOUND_PREGNANCY_INFO';
export const ERR_NOT_FOUND_PREGNANCY_DATA = 'ERR_NOT_FOUND_PREGNANCY_DATA';
export const ERR_PUSH_NOTIFICATION_STOPPED_CONDITIONS = 'ERR_PUSH_NOTIFICATION_STOPPED_CONDITIONS';

export const ERR_MAUTIC = 'ERR_MAUTIC';

export const ERR_NOT_FOUND = 'ERR_NOT_FOUND';
export const ERR_CREATE_CHILD = 'ERR_CREATE_CHILD';
export const ERR_MERGE_USERS_DATA = 'ERR_MERGE_USERS_DATA';

export const ERR_NOT_FOUND_ENTRY_CATEGORY = 'ERR_NOT_FOUND_ENTRY_CATEGORY';
export const ERR_NOT_FOUND_ENTRY = 'ERR_NOT_FOUND_ENTRY';
export const ERR_NOT_FOUND_CHALLENGE = 'ERR_NOT_FOUND_CHALLENGE';
export const ERR_NOT_FOUND_CHALLENGE_FOR_USER = 'ERR_NOT_FOUND_CHALLENGE_FOR_USER';
export const ERR_NOT_FAILED_TO_START_CHALLENGE = 'ERR_NOT_FAILED_TO_START_CHALLENGE';
export const ERR_FAILED_START_CHALLENGE = 'ERR_FAILED_START_CHALLENGE';
export const ERR_FAILED_CREATE_USER_CHALLENGE = 'ERR_FAILED_CREATE_USER_CHALLENGE';
export const ERR_FAILED_UPDATE_USER_CHALLENGE_TRACKING = 'ERR_FAILED_UPDATE_USER_CHALLENGE_TRACKING';
export const ERR_NOT_FOUND_INSIGHT = 'ERR_NOT_FOUND_INSIGHT';
export const ERR_CHALLENGE_TRANSLATION_ALREADY_EXIST = 'ERR_CHALLENGE_TRANSLATION_ALREADY_EXIST';
export const ERR_USE_CASE_TRANSLATION_ALREADY_EXIST = 'ERR_USE_CASE_TRANSLATION_ALREADY_EXIST';
export const ERR_NOT_VALID_JSON_STRUCTURE = 'ERR_NOT_VALID_JSON_STRUCTURE';
export const ERR_NOT_FOUND_CONTENT = 'ERR_NOT_FOUND_CONTENT';
export const ERR_USE_CASE_NOT_MATCH_ENTRY_CATEGORY = 'ERR_USE_CASE_NOT_MATCH_ENTRY_CATEGORY';
export const ERR_INGISHT_REQUIRE_USER_DATA_TYPE_TO_EXECUTE = 'ERR_INGISHT_REQUIRE_USER_DATA_TYPE_TO_EXECUTE';
export const ERR_NOT_FOUND_TASK = 'ERR_NOT_FOUND_TASK';
export const ERR_TOO_SMALL_ENTRY = 'ERR_TOO_SMALL_ENTRY';
