export enum GradientBgType {
  GRADIENT1 = 'GRADIENT1',
  GRADIENT2 = 'GRADIENT2',
  GRADIENT3 = 'GRADIENT3',
  GRADIENT4 = 'GRADIENT4',
  GRADIENT5 = 'GRADIENT5',
  GRADIENT6 = 'GRADIENT6',
  GRADIENT7 = 'GRADIENT7',
}
